# Generated by dynamic builder
# source: protos/signer.proto

require "google/protobuf"

# Pool nuevo que sí expone el método build
pool = Google::Protobuf::DescriptorPool.new
pool.build do
  add_file("signer.proto", syntax: :proto3) do
    add_message "signer.SignRequest" do
      optional :s3_url, :string, 1
      optional :output_key, :string, 2
    end
    add_message "signer.SignResponse" do
      optional :success, :bool,   1
      optional :signed_url, :string, 2
      optional :error,      :string, 3
    end
  end
end

# Genera las clases Ruby a partir del pool
module Signer
  SignRequest  = pool.lookup("signer.SignRequest").msgclass
  SignResponse = pool.lookup("signer.SignResponse").msgclass
end
