# Generated by the gRPC Ruby plugin. DO NOT EDIT!
# source: protos/signer.proto

require "grpc"
require_relative "signer_pb"

module Signer
  module Signer
    class Service
      include GRPC::GenericService

      self.service_name           = "signer.Signer"
      self.marshal_class_method   = :encode
      self.unmarshal_class_method = :decode

      rpc :SignPdf, SignRequest, SignResponse
    end

    Stub = Service.rpc_stub_class
  end
end
